### ISSUE TITLE
Sandbox счет уходит в минус

### ISSUE THREAD

**Issue by ivan-bezyazychnyy** [Tinkoff/invest-robot-contest#11]
На sandbox счете по ошибке выполнил несколько market ордеров и все выполнились, переведя счет в минус:
`PositionsResponse(money=[MoneyValue(currency='rub', units=-461, nano=-200000000)], blocked=[], securities=`

**Comment by AlexanderVolkovTCS** [comment]
Все верно, песочница допускает ухода позиций в минус для удобства расчета доходности/убытков стратегий.
