### ISSUE TITLE
Опенсорсить хорошего бота никто не будет

### ISSUE THREAD

**Issue by newmen** [Tinkoff/invest-robot-contest#8]
Нет, ну правда.

Опенсорсить рабочее решение, которое ты колбасил ночами, и которое реально приносит деньги – вряд ли здравая мысль. Какую-нибудь студенческую поделку на ≈ 2к строчек конечно все захотят заопенсорсить, в надежде, что прийдут другие молодцы и помогут дотолкать это до стабильного беспроигрышного результата... Но действительно гениальных решений тут скорее всего не будет.

Текстовое описание "стратегии" ещё куда не шло. Я бы вкратце описал свою, но опенсорсить решение забесплатно.. Спасибо нет :) 

Хитрецы в общем :)
И баги все найдут (если найдут).
И новые гениальные решения получат (если их сюда принесут).

**Comment by newmen** [comment]
Ах. Только после всего написаного осознал, что задача то стоит просто лучший пример получить. Который вроде и работает. И простой. И описан хорошо, чтобы другие садились на апи.
Что ж, здраво!
Спасибо кстати за долгожданное новое апи!

PS. Как насчёт номинации на Clojure? :)

**Comment by AlexanderVolkovTCS** [comment]
>просто лучший пример получить

Верно, никто не просит ключи от квартиры, где деньги лежат =)
Доходность стратегии не является критерием определения победителя, наша цель - получить хорошо описанный пример кода на разных языков и вознаградить лучших авторов за это.

>PS. Как насчёт номинации на Clojure? :)
 
Clojure в номинации по языкам нет, но вы можете предложить решение в двух последних номинациях на любом языке.
