### ISSUE TITLE
Вопросы по контесту

### ISSUE THREAD

**Issue by Ne7Le4DeR** [Tinkoff/invest-robot-contest#9]
1) Может ли один робот участвовать в нескольких номинациях? К примеру, сразу в трех:
Лучший пример торгового робота на языке js
Лучший интерфейс (визуализация) торговой стратегии
Самое оригинальное использование API Тинькофф Инвестиций

2) По критерию оценки победителей "Наличие исполненных ордеров у робота":
Выставленные поручения засчитываются только при запуска робота на реальном торговом счете или виртуальном (sandbox) тоже?
За какой период времени производятся замеры по количеству поручений от торгового робота?

3) Можно ли использовать несколько технологий (React + node, например)? Как оформлять такое решение, в виде отдельных репозиториев?

**Comment by siandreev** [comment]
В категории решений на JavaScript участвует TypeScript и фреймворки (например, NestJS)?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, спасибо за хорошие вопросы.

1. Да, может.
2. На реальной бирже. Замер производится за все время конкурса.
3. Можно.
Документацию обновили.

>В категории решений на JavaScript участвует TypeScript и фреймворки (например, NestJS)?

Да, участвуют.
